stateDiagram-v2
    [*] --> Welcome
    Welcome --> ItemSelected : Usuário Seleciona sumarização
    ItemSelected --> Welcome : Deseleciona item
    ItemSelected --> MainView : Clica criar nova conversa
